hibernate:
  connection:
    driver_class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/user_service
    username: postgres
    password: admin
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: update
